language: node_js
node_js:
  - '5'
before_script:
  - npm install  
  - bower install
services:
  - mongodb
deploy:
  provider: openshift
  user: $EMAIL_ADDRESS
  password: decline182
  app: $APP_NAME
  domain: $DOMAIN_NAME
  on: master
